### ISSUE TITLE
Generate histograms

### ISSUE THREAD

**Issue by alx3416** [alx3416/CienciaDatos2024-1#5]
Generate histograms from diabetes dataset

Adding a kde (kernel density estimate) it's a good plus for this one
![image](https://github.com/alx3416/CienciaDatos2024-1/assets/63263335/34d2e8e1-0f4a-41c8-9e63-515bb74d5d6e)

**Comment by 21Hell** [comment]
![Screenshot from 2024-02-16 18-22-48](https://github.com/alx3416/CienciaDatos2024-1/assets/76609684/4dc1ca62-0528-4836-9f5e-fdaf98a44654)
